name: Sample Doppler Secrets Access
on: [push]

jobs:
    main:
        runs-on: ubuntu-latest # ubuntu, macos, and windows are supported
        steps:
            - name: Test Doppler Access
              run: printenv | grep FOO
